---
# tasks file for ec2-delete

- name: Collect running instances and collect the IDs
  ec2_instance_facts:
    filters:
      instance-state-name: "running"
      "tag:Name": '*'
    region: "{{ aws_region }}"
  register: ec2_running

- name: delete servers
  ec2:
    key_name: "{{ ec2_key_name }}"
    instance_ids: "{{ ec2_running['instances'][0]['instance_id'] }}"
    instance_tags:
      Name: Webserver
    state: absent
    region: "{{ aws_region }}"
  when:  ec2_running['instances'][0] is defined and ec2_running['instances'][0]['instance_id'] is defined
  with_items: "{{ec2_running.instances}}"
  register: ec2_running

- debug:
    var: ec2_running



- name: Collect stopped instances and collect the IDs
  ec2_instance_facts:
    filters:
      instance-state-name: "stopped"
      "tag:Name": "*"
    region: "{{ aws_region }}"
  register: ec2_stopped

- name: delete servers
  ec2:
    key_name: "{{ ec2_key_name }}"
    instance_ids: "{{ ec2_stopped['instances'][0]['instance_id'] }}"
    instance_tags:
      Name: '*'
    state: absent
    region: "{{ aws_region }}"
  when:  ec2_stopped['instances'][0] is defined and ec2_stopped['instances'][0]['instance_id'] is defined
  with_items: "{{ec2_stopped.instances}}"
  register: ec2_stopped

- debug:
    var: ec2_stopped
